stages:
  # - test
  - build
  - deploy
  - release

# sast:
#   stage: test

include:
  # - template: Security/SAST.gitlab-ci.yml
  - local: /.gitlab/variables.yml
  - local: /.gitlab/build.yml
  - local: /.gitlab/staging.yml
  - local: /.gitlab/production.yml
  - local: /.gitlab/release.yml