.production_rule:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == "main" && $CI_DEPLOY_FREEZE == null'

.production_environment:
  environment:
    name: production
    url: $ProductionURL

build_production:
  extends:
    - .build
    - .production_rule
    - .production_environment
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.build.yml build
    - docker-compose -f docker-compose.yml -f docker-compose.build.yml push
  artifacts:
    paths:
      - docker-compose.yml

deploy_production:
  extends:
    - .production_rule
    - .production_environment
  stage: deploy
  before_script:
    - echo $CI_REGISTRY_PASSWORD | sudo docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - sudo docker pull $CONVOFrontend
  script:
    - sudo -E docker-compose up -d
  after_script:
    - sudo docker image prune -f -a
    - sudo docker logout
  tags:
    - convoportal
    - production
    - front-end
  variables:
    GIT_STRATEGY: none
